# Generated by Django 5.2.8 on 2025-11-07 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512, verbose_name="ファイルパス")),
                (
                    "size",
                    models.BigIntegerField(default=0, verbose_name="ファイルサイズ"),
                ),
                ("checksum", models.CharField(max_length=128, verbose_name="ハッシュ")),
                (
                    "source",
                    models.CharField(blank=True, max_length=128, verbose_name="取得元"),
                ),
                ("format", models.CharField(max_length=32, verbose_name="形式")),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="メタ情報"),
                ),
            ],
            options={
                "verbose_name": "ファイルメタ情報",
                "verbose_name_plural": "ファイルメタ情報",
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=32, verbose_name="ステータス"
                    ),
                ),
                (
                    "report",
                    models.JSONField(blank=True, default=dict, verbose_name="レポート"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="ingestion.filemetadata",
                    ),
                ),
                (
                    "measurement_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="datasets.measurementset",
                    ),
                ),
            ],
            options={
                "verbose_name": "取込ジョブ",
                "verbose_name_plural": "取込ジョブ",
                "ordering": ["-created_at"],
            },
        ),
    ]
