# Generated by Django 5.2.8 on 2025-11-07 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="ラベル名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="メタ情報"),
                ),
            ],
            options={
                "verbose_name": "ラベル",
                "verbose_name_plural": "ラベル",
            },
        ),
        migrations.CreateModel(
            name="LabelSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="スキーマ名")),
                (
                    "tree_path",
                    models.CharField(
                        help_text="ドット区切りで階層を定義します。",
                        max_length=512,
                        verbose_name="ツリー構造",
                    ),
                ),
                (
                    "rules",
                    models.JSONField(blank=True, default=dict, verbose_name="ルール"),
                ),
            ],
            options={
                "verbose_name": "ラベルスキーマ",
                "verbose_name_plural": "ラベルスキーマ",
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_range",
                    models.JSONField(blank=True, default=dict, verbose_name="時間範囲"),
                ),
                ("note", models.TextField(blank=True, verbose_name="ノート")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=32, verbose_name="バージョン"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel_map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="datasets.channelmap",
                    ),
                ),
                (
                    "measurement_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="datasets.measurementset",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="labeling.label",
                    ),
                ),
            ],
            options={
                "verbose_name": "アノテーション",
                "verbose_name_plural": "アノテーション",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="label",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="labeling.labelschema",
            ),
        ),
    ]
