# Generated by Django 5.2.8 on 2025-11-07 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                (
                    "spec",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="チャート仕様"
                    ),
                ),
                (
                    "datasource_ref",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="データソース参照"
                    ),
                ),
                (
                    "snapshot_html",
                    models.TextField(blank=True, verbose_name="Plotly HTML"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_charts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "保存済みチャート",
                "verbose_name_plural": "保存済みチャート",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="タイトル")),
                (
                    "layout",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="レイアウト"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "charts",
                    models.ManyToManyField(
                        blank=True, related_name="dashboards", to="analytics.savedchart"
                    ),
                ),
            ],
            options={
                "verbose_name": "ダッシュボード",
                "verbose_name_plural": "ダッシュボード",
            },
        ),
    ]
