# Generated by Django 5.2.8 on 2025-11-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ECU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="ECU名称")),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ファームウェア"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="メタ情報"),
                ),
            ],
            options={
                "verbose_name": "ECU",
                "verbose_name_plural": "ECU",
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="センサー名")),
                ("sensor_type", models.CharField(max_length=64, verbose_name="種類")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="単位"),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="メタ情報"),
                ),
            ],
            options={
                "verbose_name": "センサー",
                "verbose_name_plural": "センサー",
            },
        ),
        migrations.CreateModel(
            name="TestCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="試験コース")),
                (
                    "location",
                    models.CharField(blank=True, max_length=128, verbose_name="所在地"),
                ),
                (
                    "environment",
                    models.JSONField(blank=True, default=dict, verbose_name="環境情報"),
                ),
            ],
            options={
                "verbose_name": "テストコース",
                "verbose_name_plural": "テストコース",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="VIN",
                    ),
                ),
                (
                    "model_code",
                    models.CharField(max_length=64, verbose_name="モデルコード"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="年式"
                    ),
                ),
                (
                    "powertrain",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="パワートレイン",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=dict, verbose_name="タグ"),
                ),
            ],
            options={
                "verbose_name": "車両",
                "verbose_name_plural": "車両",
                "ordering": ["model_code", "year"],
            },
        ),
    ]
